### ISSUE TITLE
Do not fail on duplicate datasource entries

### ISSUE THREAD

**Issue by RubenVerborgh** [LinkedDataFragments/jQuery-Widget.js#10]
As discussed in https://github.com/LinkedDataFragments/jQuery-Widget.js/issues/9#issuecomment-324930376, the widget should not fail when a datasource occurs multiple times. I would propose to not fail, but just read the first definition.

**Comment by rubensworks** [comment]
Resolved by 30022745bc5337e4be7841a30d053a79c2660608
