### ISSUE TITLE
npm run production only works with Node 8, not later versions

### ISSUE THREAD

**Issue by ColinMaudry** [LinkedDataFragments/jQuery-Widget.js#13]
Hello,

I have run `npm run production` with Node 10, and it resulted in the following error:

```
> gulp build --production

gulp[1012]: ../src/node_contextify.cc:633:static void node::contextify::ContextifyScript::New(const v8::FunctionCallbackInfo<v8::Value>&): Assertion `args[1]->IsString()' failed.
 1: 0x8db900 node::Abort() [gulp]
 2: 0x8db9d5  [gulp]
 3: 0x90f697 node::contextify::ContextifyScript::New(v8::FunctionCallbackInfo<v8::Value> const&) [gulp]
 4: 0xb5df6b  [gulp]
 5: 0xb5ff02 v8::internal::Builtin_HandleApiCall(int, v8::internal::Object**, v8::internal::Isolate*) [gulp]
 6: 0x21406585be1d 
Aborted (core dumped)
```

Switching to Node 8 worked.

According to [certain StackOverflow thread](https://stackoverflow.com/questions/50199303/node-js-v10-0-0-messing-with-gulp), it may be related to the version of Gulp you use.

FYI I'm currently trying to integrate the widget in a Vue component.

**Comment by rubensworks** [comment]
Hi @ColinMaudry. You may be interested in our new Comunica engine, which also has a similar jQuery widget: https://github.com/comunica/jQuery-Widget.js
It is functionally equivalent to LDF Client, and can do a bit more.
This has been tested to work on Node 10, and does not use Gulp anymore.

@RubenVerborgh Shall we still maintain this repo? Or mark it as deprecated?

**Comment by RubenVerborgh** [comment]
Deprecating is fine.

**Comment by ColinMaudry** [comment]
@rubensworks Can you be more specific on the "bit more" that Comunica can do compared with the LDF client?

**Comment by rubensworks** [comment]
@ColinMaudry The main difference is that LDF Client works with TPF interfaces only, while Comunica works with TPF, SPARQL, Linked Data Documents, ...

More information here: http://comunica.linkeddatafragments.org/

**Comment by ColinMaudry** [comment]
Wow, OK, I thought LDF did it already. Great, can't wait to push it to the limits :)

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by pheyvaer** [comment]
So will this repo be archived? Or can we at least have a disclaimer in the README that points to the Comunica widget?

**Comment by rubensworks** [comment]
We probably should, also for Client.js.
@RubenVerborgh Do you agree?

**Comment by RubenVerborgh** [comment]
Agree to archive this repo, and also add the link.

@rubensworks Is there _any_ reason why one could still want to use Client.js (other than benchmarking legacy)?

**Comment by rubensworks** [comment]
> Is there any reason why one could still want to use Client.js (other than benchmarking legacy)?

I don't think so. As far as I know, everything that Client.js can do, can also be done by Comunica.

**Comment by RubenVerborgh** [comment]
OK, let's proceed with archiving both, adding an explanation to the README of why. Let's create an issue for that in both repos and assign.

**Comment by rubensworks** [comment]
This repo has now officially been deprecated.
Please use https://github.com/comunica/jQuery-Widget.js instead.
