### ISSUE TITLE
Cannot erase datasource http://data.linkeddatafragments.org/lov

### ISSUE THREAD

**Issue by cKlee** [LinkedDataFragments/jQuery-Widget.js#9]
I cannot erase the datasource LOV/Linked Open Vocabularies. Even when another datasource was chosen. Also not working when reloading with datasources=...

In FF and IE

![clipboard01](https://user-images.githubusercontent.com/849235/29713891-00e7f95a-89a1-11e7-8dc8-f400823cbddc.png)

Just pulled from master.

**Comment by rubensworks** [comment]
Are you seeing any errors in the JavaScript console?
What Firefox version are you using?

Seems to work fine for me on both Chrome 60.0.3112.101 and Firefox 54.0.1 (Mac) from the `master` branch and http://client.linkeddatafragments.org/.

**Comment by RubenVerborgh** [comment]
Also, how are you running the client? Did you set up a local HTTP server?

**Comment by cKlee** [comment]
Yes a local server (npm start). Console output

```
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:14:5016
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:14:6112
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:24:204
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:24:214
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:24:3703
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:24:15255
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:24:62736
15:30:16.172 SyntaxError: test for equality (==) mistyped as assignment (=)? ldf-client-ui.min.js:41:20239
15:30:16.172 TypeError: variable n redeclares argument ldf-client-ui.min.js:60:10180
15:30:16.195 ReferenceError: reference to undefined property n[t] ldf-client-ui.min.js:24:25870
15:30:16.197 ReferenceError: reference to undefined property this[n] ldf-client-ui.min.js:24:19395
15:30:16.210 ReferenceError: reference to undefined property n[_e.expando] ldf-client-ui.min.js:24:39857
15:30:16.215 ReferenceError: reference to undefined property K.event.triggered ldf-client-ui.min.js:24:31235
15:30:16.216 ReferenceError: reference to undefined property e.nodeType ldf-client-ui.min.js:24:25353
15:30:16.231 ReferenceError: reference to undefined property this.items_[(this.loadedItems_ - 1)] ldf-client-ui.min.js:60:3379
15:30:16.232 ReferenceError: reference to undefined property s.selectedDatasources ldf-client-ui.min.js:62:3608
15:30:16.232 ReferenceError: reference to undefined property K.event.triggered ldf-client-ui.min.js:24:29609
15:30:16.235 ReferenceError: reference to undefined property this._querySetId ldf-client-ui.min.js:62:6466
15:30:16.237 ReferenceError: reference to undefined property i.query ldf-client-ui.min.js:62:1
15:30:16.237 ReferenceError: reference to undefined property s.type ldf-client-ui.min.js:24:56868
15:30:16.238 ReferenceError: reference to undefined property h.headers ldf-client-ui.min.js:24:62377
15:30:16.238 ReferenceError: reference to undefined property e.username ldf-client-ui.min.js:24:65746
15:30:16.331 ReferenceError: reference to undefined property n.query ldf-client-ui.min.js:62:6022
15:30:16.364 ReferenceError: reference to undefined property e[x.status] ldf-client-ui.min.js:24:61199

```

But nothing else when clicking on X to erase source.

I don't know if this has something to do with my apache reverse proxy settings.

But when I access the client it looks like

![clipboard02](https://user-images.githubusercontent.com/849235/29716394-873e1eda-89ab-11e7-96b8-6c20d91ef71c.png)

When I try to erase LOV, on click URL jumps to

    /client/#transientDatasources=http%3A%2F%2Ffragments.dbpedia.org%2F2016-04%2Fen

but LOV is still there. When executing a query LOV gets requested.

If I erase DBPedia, URL jumps to

    client/#datasources=http%3A%2F%2Fdata.linkeddatafragments.org%2Flov

and another bubble "Linked Open Vocabularies" is displayed.

![clipboard01](https://user-images.githubusercontent.com/849235/29716781-f73d8634-89ac-11e7-90bd-e436e3b11bb4.png)

FF 45.2
IE 11
Chrome 60

**Comment by RubenVerborgh** [comment]
Okay, this is _very_ weird. Before we go on, let me make sure we're all using the exact same dependencies. Just a sec.

**Comment by RubenVerborgh** [comment]
There's a package-lock.json in the repository, so that should work. Can you use Node 8.x, `rm -rf node_modules; npm install`?

**Comment by RubenVerborgh** [comment]
Also, can we have your exact configuration? Because `LOV` is not in the default configuration. I'm suspecting now that you have duplicate entries for LOV, but that doesn't explain everything.

**Comment by cKlee** [comment]
Yep! This was the problem. I had duplicate entries for LOV. Now everything works like expected. Thanks!

**Comment by rubensworks** [comment]
We should probably add a config integrity check for avoiding issues like these in the future.
